/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesinvoice.view;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import salesinvoice.controller.controller;
import salesinvoice.model.invoiceDetailsTable;
import salesinvoice.model.invoiceHeader;
import salesinvoice.model.invoiceLine;
import salesinvoice.model.invoiceTable;

/**
 *
 * @author yogy7
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        allInvoicesTable = new javax.swing.JTable();
        allInvoicesTable.getSelectionModel().addListSelectionListener(control);
        createNewInvoice = new javax.swing.JButton();
        createNewInvoice.addActionListener(control);
        deleteInvoice = new javax.swing.JButton();
        deleteInvoice.addActionListener(control);
        invoiceNumberLable = new javax.swing.JLabel();
        invoiceDateLabel = new javax.swing.JLabel();
        CustomerNameLabel = new javax.swing.JLabel();
        invoiceTotalLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InvoceItems = new javax.swing.JTable();
        invoiceItemSection = new javax.swing.JLabel();
        saveChanges = new javax.swing.JButton();
        saveChanges.addActionListener(control);
        discardChanges = new javax.swing.JButton();
        discardChanges.addActionListener(control);
        dateDataLabel = new javax.swing.JLabel();
        customerNameDataLabel = new javax.swing.JLabel();
        numLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        customerLabel = new javax.swing.JLabel();
        totalLable = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MI1loadfile = new javax.swing.JMenuItem();
        MI1loadfile.addActionListener(control);
        MI2SaveFile = new javax.swing.JMenuItem();
        MI2SaveFile.addActionListener(control);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        allInvoicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(allInvoicesTable);
        if (allInvoicesTable.getColumnModel().getColumnCount() > 0) {
            allInvoicesTable.getColumnModel().getColumn(3).setResizable(false);
        }

        createNewInvoice.setText("Create New Invoice");
        createNewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewInvoiceActionPerformed(evt);
            }
        });

        deleteInvoice.setText("Delete Invoice");

        invoiceNumberLable.setText("Invoice Number");

        invoiceDateLabel.setText("Invoice Date");

        CustomerNameLabel.setText("Customer Name");

        invoiceTotalLabel.setText("Invoice Total");

        InvoceItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(InvoceItems);

        invoiceItemSection.setText("Invoice Items");

        saveChanges.setText("Add new Item");
        saveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesActionPerformed(evt);
            }
        });

        discardChanges.setText("Delete Item");
        discardChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardChangesActionPerformed(evt);
            }
        });

        numLabel.setText("     ");

        dateLabel.setText("    ");

        customerLabel.setText("     ");

        totalLable.setText("    ");

        jMenu1.setText("File");

        MI1loadfile.setText("Load File");
        MI1loadfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI1loadfileActionPerformed(evt);
            }
        });
        jMenu1.add(MI1loadfile);

        MI2SaveFile.setText("Save File");
        MI2SaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI2SaveFileActionPerformed(evt);
            }
        });
        jMenu1.add(MI2SaveFile);

        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(createNewInvoice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteInvoice)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(invoiceNumberLable)
                                    .addComponent(invoiceTotalLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(saveChanges)
                                .addGap(18, 18, 18)
                                .addComponent(discardChanges))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(invoiceItemSection)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(invoiceDateLabel)
                                        .addComponent(CustomerNameLabel)))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dateLabel)
                                    .addComponent(customerLabel)
                                    .addComponent(totalLable)
                                    .addComponent(numLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateDataLabel)
                                    .addComponent(customerNameDataLabel))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceNumberLable)
                            .addComponent(numLabel))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceDateLabel)
                            .addComponent(dateDataLabel)
                            .addComponent(dateLabel))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerNameLabel)
                            .addComponent(customerNameDataLabel)
                            .addComponent(customerLabel))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceTotalLabel)
                            .addComponent(totalLable))
                        .addGap(33, 33, 33)
                        .addComponent(invoiceItemSection)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(createNewInvoice)
                        .addComponent(deleteInvoice))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(discardChanges)
                        .addComponent(saveChanges)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createNewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewInvoiceActionPerformed
    }//GEN-LAST:event_createNewInvoiceActionPerformed

    private void saveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveChangesActionPerformed

    private void discardChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardChangesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discardChangesActionPerformed

    private void MI1loadfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI1loadfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MI1loadfileActionPerformed

    private void MI2SaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI2SaveFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MI2SaveFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JTable InvoceItems;
    private javax.swing.JMenuItem MI1loadfile;
    private javax.swing.JMenuItem MI2SaveFile;
    private javax.swing.JTable allInvoicesTable;
    private javax.swing.JButton createNewInvoice;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JLabel customerNameDataLabel;
    private javax.swing.JLabel dateDataLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton deleteInvoice;
    private javax.swing.JButton discardChanges;
    private javax.swing.JLabel invoiceDateLabel;
    private javax.swing.JLabel invoiceItemSection;
    private javax.swing.JLabel invoiceNumberLable;
    private javax.swing.JLabel invoiceTotalLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel numLabel;
    private javax.swing.JButton saveChanges;
    private javax.swing.JLabel totalLable;
    // End of variables declaration//GEN-END:variables

    
    private ArrayList<invoiceHeader> headers;
private controller control = new controller(this);
private invoiceTable invoiceTable;
    public ArrayList<invoiceHeader> getHeaders() {
        if (headers == null) headers = new ArrayList<>();
        return headers;
    }
    
  
    
    
    
private invoiceTable invoicesTableModel;
    public void setHeaders(ArrayList<invoiceHeader> headers) {
        this.headers = headers;
    }
  
    
    

    public invoiceTable getInvoicesTableModel() {
        if(invoicesTableModel == null)
        {
        invoicesTableModel = new invoiceTable(getHeaders());
        }
        return invoicesTableModel;
    }
    
    

    public void setInvoicesTableModel(invoiceTable invoicesTableModel) {
        this.invoicesTableModel = invoicesTableModel;
    }

    


    public JLabel getCustomerNameLabel() {
        return CustomerNameLabel;
    }

    public JTable getInvoceItems() {
        return InvoceItems;
    }


    public JLabel getCustomerLabel() {
        return customerLabel;
    }

    public JLabel getDateLabel() {
        return dateLabel;
    }

    public JLabel getNumLabel() {
        return numLabel;
    }

    public JLabel getTotalLable() {
        return totalLable;
    }
    

    public controller getControl() {
        return control;
    }

    public JTable getAllInvoicesTable() {
        return allInvoicesTable;
    }
    
    public int getHighstInvoiceNumber ()
    {
        int number = 0;
        
       for (invoiceHeader highstNumber : getHeaders())
       {
          if(highstNumber.getNum() > number)
              number = highstNumber.getNum();
          
       }
        return ++number;
    }
    
} 


